### ISSUE TITLE
search and highlight text

### ISSUE THREAD

**Issue by gennaro-tedesco** [Textualize/frogmouth#41] opened 2023-05-10 01:09 UTC
### Feature request 

Would it be possible to introduce a mechanism to search and highlight (searched) text? I do not know if Textualize enables such a thing easily enough, however noticing that all other terminal pagers do I thought it could be a feature that should somehow be proposed :).

Along the same lines of [this other issue](https://github.com/Textualize/frogmouth/issues/14) other terminal pagers (see `less` for example) default the search to `/` á la vim: given that other vim bindings are included by default (as you mention in the comments of that issue), I was wondering if there is a particular reason why `/` currently invokes the title bar instead?

**Comment by davep** [comment] 2023-05-10 06:41
Something I plan on adding, see #16.

Closing this as a duplicate of that.

**Closed by davep** 2023-05-10 06:41 UTC
Labels: duplicate
