### ISSUE TITLE
Support HTML

### ISSUE THREAD

**Issue by BenStigsen** [Textualize/frogmouth#81] opened 2023-10-05 11:52 UTC
HTML support would transform this into a powerful TUI browser, with easy chapter navigation which isn't standard in browsers, but very very useful.

Using a tool like `markdownify` to convert HTML to Markdown, would transform Frogmouth into a general purpose browser, yet leave things as is in terms of compatibility.

**Comment by davep** [comment] 2023-10-05 11:54
Thanks. Closing as a duplicate of #64.

**Comment by BenStigsen** [comment] 2023-10-05 11:54
Ah, sorry about that. I searched specifically for HTML which is why I missed it.

**Closed by davep** 2023-10-05 11:54 UTC
Labels: duplicate
