### ISSUE TITLE
Add support to launch $EDITOR?

### ISSUE THREAD

**Issue by khughitt** [Textualize/frogmouth#18] opened 2023-04-30 21:30 UTC
If so, binding it to "e" would be a really convenient way to open the document in an editor.

At least on Linux, [click.edit](https://click.palletsprojects.com/en/8.1.x/utils/#launching-editors) works pretty well for this.

```
click.edit(filename=...)
```

I haven't tried it on other systems though so I'm sure there could be some limitations.

Thanks again!

Cheers,
Keith

**Comment by davep** [comment] 2023-04-30 21:32
Closing as a duplicate of #11.

**Closed by davep** 2023-04-30 21:32 UTC
Labels: duplicate

**Comment by khughitt** [comment] 2023-05-02 00:35
Thought I checked for this, too. Sorry for missing that!
